### ISSUE TITLE
14-Kanban-DataLayer

### ISSUE THREAD

**Issue by Nbhaskell** [OriginCodeAcademy/2016-Winter-Cohort#140]
1. Where can I find your repository?
https://github.com/Nbhaskell/14-Kanban-DataLayer
2. How did you create the SQL Database? Through scripts or through the GUI?
Scripts
3. On a scale of 1-10, how would you rate the difficulty of this assignment?
5. It was pretty straight forward but we did get stuck in a couple of places with syntax errors.

**Comment by cameronoca** [comment]
Would like to see some more issues from you sir!
